package casestudy;

import java.sql.*;

public class DatabaseManager {
    private Connection conn;

    public DatabaseManager() {
        try {
            String user = "system";
            String password = "manager";
            String url = "jdbc:oracle:thin:@localhost:1521:xe";

            conn = DriverManager.getConnection(url, user, password);

            // Check if table exists, create if not
            if (!tableExists("WATER_QUALITY")) {
                createTable();
            }

        } catch (SQLException e) {
            System.out.println("Connection error: " + e);
        }
    }

    // Method to check if table exists
    private boolean tableExists(String tableName) {
        boolean exists = false;
        ResultSet rs = null;
        PreparedStatement pstmt = null;
        try {
            String checkQuery = "SELECT table_name FROM user_tables WHERE table_name = ?";
            pstmt = conn.prepareStatement(checkQuery);
            pstmt.setString(1, tableName.toUpperCase());
            rs = pstmt.executeQuery();

            if (rs.next()) {
                exists = true; // Table exists
            }

        } catch (SQLException e) {
            System.out.println("Error checking table existence: " + e);
        } finally {
            try {
                if (rs != null) rs.close();
                if (pstmt != null) pstmt.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
        return exists;
    }

    // Method to create the table
    private void createTable() {
        Statement stmt = null;
        try {
            stmt = conn.createStatement();
            String createTableSQL = "CREATE TABLE water_quality (" +
                    "id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "pH NUMBER, " +
                    "turbidity NUMBER, " +
                    "oxygen NUMBER, " +
                    "temp NUMBER, " +
                    "status VARCHAR2(50))";
            stmt.executeUpdate(createTableSQL);
            System.out.println("Table WATER_QUALITY created successfully.");
        } catch (SQLException e) {
            System.out.println("Error creating table: " + e);
        } finally {
            try {
                if (stmt != null) stmt.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }

    // Method to insert a record
    public void saveResult(double pH, double turbidity, double oxygen, double temp, String status) {
        PreparedStatement pstmt = null;
        try {
            String insertSQL = "INSERT INTO water_quality (pH, turbidity, oxygen, temp, status) VALUES (?, ?, ?, ?, ?)";
            pstmt = conn.prepareStatement(insertSQL);
            pstmt.setDouble(1, pH);
            pstmt.setDouble(2, turbidity);
            pstmt.setDouble(3, oxygen);
            pstmt.setDouble(4, temp);
            pstmt.setString(5, status);
            pstmt.executeUpdate();
            System.out.println("Record inserted successfully.");
        } catch (SQLException e) {
            System.out.println("Insert error: " + e);
        } finally {
            try {
                if (pstmt != null) pstmt.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }

    // Close connection when done
    public void close() {
        try {
            if (conn != null && !conn.isClosed()) {
                conn.close();
                System.out.println("Connection closed.");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    // Example usage
    public static void main(String[] args) {
        DatabaseManager db = new DatabaseManager();

        // Insert a sample record
        db.saveResult(7.2, 0.5, 6.8, 25.0, "Safe");

        db.close();
    }
}